### ISSUE TITLE
Confused about PIN 0

### ISSUE THREAD

**Issue by nsmith1024** [Patryk27/Omega2-GPIO#4]
In your led-blink.cpp example you mentioned LED 0

const uint8_t LED_PIN = 0;

What does that mean exactly? which pin is that? is there a pin 0 on omega2+?
Can you explain what this means?
Thanks

**Comment by Patryk27** [comment]
Hi,

As far as I remember, this corresponds to the same pin numbering that's used by `gpioctl`, which is the same as on the pinout diagram:

![image](https://user-images.githubusercontent.com/3395477/202376796-83751e07-18e6-4b39-999a-2c419775859f.png)

(https://docs.onion.io/omega2-docs/using-gpios.html)

🙂
